// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7lMlJdULr1Y3kBGJqAaLTophhZh1hEPg',
    appId: '1:942785216283:web:5b77ec16a63e42ef361dbe',
    messagingSenderId: '942785216283',
    projectId: 'flutter-6ebaf',
    authDomain: 'flutter-6ebaf.firebaseapp.com',
    storageBucket: 'flutter-6ebaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8ywwVUwe-Fi0HfeDkbGDlOjf-X5PcA0',
    appId: '1:942785216283:android:f9467b7ef335eeb7361dbe',
    messagingSenderId: '942785216283',
    projectId: 'flutter-6ebaf',
    storageBucket: 'flutter-6ebaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkpwxcDQUabJ7lwXof-feqHWe4HZB5qk',
    appId: '1:942785216283:ios:7ebce54347ca815d361dbe',
    messagingSenderId: '942785216283',
    projectId: 'flutter-6ebaf',
    storageBucket: 'flutter-6ebaf.firebasestorage.app',
    iosBundleId: 'com.example.fac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkpwxcDQUabJ7lwXof-feqHWe4HZB5qk',
    appId: '1:942785216283:ios:7ebce54347ca815d361dbe',
    messagingSenderId: '942785216283',
    projectId: 'flutter-6ebaf',
    storageBucket: 'flutter-6ebaf.firebasestorage.app',
    iosBundleId: 'com.example.fac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7lMlJdULr1Y3kBGJqAaLTophhZh1hEPg',
    appId: '1:942785216283:web:873c3755d9c125b7361dbe',
    messagingSenderId: '942785216283',
    projectId: 'flutter-6ebaf',
    authDomain: 'flutter-6ebaf.firebaseapp.com',
    storageBucket: 'flutter-6ebaf.firebasestorage.app',
  );
}
